### ISSUE TITLE
missing ResourceBundleMessageSource

### ISSUE THREAD

**Issue by JoppeKoning** [yoep/spring-boot-starter-javafx#5]
Hi Yoep,

I was unable to use your library directly. It gave me this error:
"Error creating bean with name 'localeText' defined in class path resource [com/github/spring/boot/javafx/text/config/LocaleTextConfiguration.class]: Unsatisfied dependency expressed through method 'localeText' parameter 0: No qualifying bean of type 'org.springframework.context.support.ResourceBundleMessageSource' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}"

Googling gave me the solution to it. Maybe it it helpful for others as well.
I followed this tutorial to add the MessageSource bean:
https://howtodoinjava.com/spring-core/resolving-text-messages-in-spring-resourcebundlemessagesource-example/

**Comment by yoep** [comment]
Hi

This is indeed a requirement for JavaFX to work correctly with text reference values in `fxml` files.
It's been reported before and answered in https://github.com/yoep/spring-boot-starter-javafx/issues/1#issuecomment-1279712377

I'll update the README documentation to make this topic a little bit more clear.
